### ISSUE TITLE
Crowdloan Rewards

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-node#16]
- [x] Vesting pallet + vesting schedule for crowdloaners #26 

- crowdloaners will authorize by signature from their KSM wallet and send a feeless transaction with their BSX wallet that will receive a vested reward

- the claims data has to be set after parachain is included

**Comment by jak-pan** [comment]
We need to check the balances with people (should be all good) only last few had less than 100% multiplier. @maht0rz @enthusiastmartin @vgantchev. 

- [ ] Let's do a short survey for people to check https://loan.bsx.fi we then take the balances and put it on-chain as vested transfer to these accounts over our period ending a month before it finishes.

- [ ] We need to forbid orml vesting interactions with call filter until we finish lbp.

**Comment by lumir-mrkva** [comment]
this was done by batch vesting all rewards to the KSM wallets
