### ISSUE TITLE
Legacy Claims

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-node#17]
Claims from HydraDX Snakenet.

**Supply will be 10 * bigger than HydraDX**

- [x] define shapshot block

### from snakenet
- [x] hdx balances claims #63 
- [x] hydradx lbp claims #69
